apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
