apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: APP_PORT
              value: "5000"
            - name: MONGO_URI
              value: mongodb://mongo:27017/todos
          image: api
          name: python-todos-api
          ports:
            - containerPort: 8090
          resources: {}
          volumeMounts:
            - mountPath: /api
              name: api-claim0
      restartPolicy: Always
      volumes:
        - name: api-claim0
          persistentVolumeClaim:
            claimName: api-claim0
status: {}
